# Generated by Django 4.1.1 on 2022-09-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothmodel',
            options={'verbose_name': 'Модель одежды', 'verbose_name_plural': 'Модели одежды'},
        ),
    ]
