# Generated by Django 4.1.1 on 2022-09-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_clothmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Таблица материалов нитей', 'verbose_name_plural': 'Таблица материалов нитей'},
        ),
    ]
