# Generated by Django 4.1.1 on 2022-09-18 12:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', verbose_name='Номер телефона')),
                ('salary', models.FloatField(default=0, verbose_name='Зарплата')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото сотр')),
            ],
        ),
    ]
