# Generated by Django 4.1.1 on 2022-09-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_options'),
        ('fabrika', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.CreateModel(
            name='MaterialTaked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taked_mass', models.FloatField(verbose_name='Взятая масса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата взятия')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.material', verbose_name='Материал')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takedadmin', to='fabrika.employee', verbose_name='Старший взял')),
            ],
            options={
                'verbose_name': 'Материал взятый старшим',
                'verbose_name_plural': 'Материалы взятые старшими',
            },
        ),
    ]
