# Generated by Django 4.1.1 on 2022-09-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0003_vyazka'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtaked',
            name='remaining_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Оставшийся материал у старшего'),
        ),
    ]
