# Generated by Django 4.1.1 on 2022-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0004_materialtaked_remaining_mass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vyazka',
            options={'verbose_name': 'Вязка метериала', 'verbose_name_plural': 'Распределение на взяку метериала'},
        ),
        migrations.AddField(
            model_name='employee',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='Отчет по зарплате'),
        ),
        migrations.AlterField(
            model_name='vyazka',
            name='count',
            field=models.IntegerField(blank=True, help_text='Заполнить после того, как работник сделал вязку', null=True, verbose_name='Количество готовой модели'),
        ),
        migrations.AlterField(
            model_name='vyazka',
            name='mass_brak',
            field=models.FloatField(default=0, help_text='Заполнить после того, как работник сделал вязку', verbose_name='Масса брака'),
        ),
        migrations.AlterField(
            model_name='vyazka',
            name='mass_finish',
            field=models.FloatField(blank=True, help_text='Заполнить после того, как работник сделал вязку', null=True, verbose_name='Готовая масса после вязки'),
        ),
    ]
