# Generated by Django 4.1.1 on 2022-09-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_rename_tutma_clothmodel_tugma_and_more'),
        ('fabrika', '0005_alter_vyazka_options_employee_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtaked',
            name='for_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.clothmodel', verbose_name='На какую модель товара взял'),
        ),
        migrations.CreateModel(
            name='ClothProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_taked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrika.vyazka', verbose_name='Из какой вязки')),
            ],
        ),
    ]
