# Generated by Django 4.1.1 on 2022-09-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0006_materialtaked_for_model_clothproductmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothproductmodel',
            options={'verbose_name': 'Процесс производства', 'verbose_name_plural': 'Процессы производства'},
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='averlock_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='averlock', to='fabrika.employee', verbose_name='Работник Аверлок'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='bichuv_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bichuv', to='fabrika.employee', verbose_name='Работник Бичув'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='chistka_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chistka', to='fabrika.employee', verbose_name='Работник Чистка'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='chok_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chok', to='fabrika.employee', verbose_name='Работник Чок'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='dazmol_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dazmol', to='fabrika.employee', verbose_name='Работник Дазмол'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='jemchug_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jemchug', to='fabrika.employee', verbose_name='Работник Жемчуг'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='katelniy_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='katelniy', to='fabrika.employee', verbose_name='Работник Кательни'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='petlya_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petlya', to='fabrika.employee', verbose_name='Работник Петля'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='tugma_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tugma', to='fabrika.employee', verbose_name='Работник Тугма'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='upakovka_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upakovka', to='fabrika.employee', verbose_name='Работник Упаковка'),
        ),
    ]
