# Generated by Django 4.1.1 on 2022-09-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0007_alter_clothproductmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='report',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Отчет по зарплате'),
        ),
    ]
