# Generated by Django 4.1.1 on 2022-09-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0008_alter_employee_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='report',
            field=models.TextField(blank=True, default='Отчет по зарплате\n', null=True, verbose_name='Отчет по зарплате'),
        ),
    ]
