# Generated by Django 4.1.1 on 2022-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0009_alter_employee_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothproductmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
