# Generated by Django 4.1.1 on 2022-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0010_clothproductmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothproductmodel',
            name='averlock_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='bichuv_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='chistka_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='chok_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='dazmol_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='jemchug_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='katelniy_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='petlya_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='tugma_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
        migrations.AddField(
            model_name='clothproductmodel',
            name='upakovka_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во изменении'),
        ),
    ]
