# Generated by Django 4.1.1 on 2022-10-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0011_clothproductmodel_averlock_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_series', models.CharField(max_length=255, verbose_name='Серия продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrika.clothproductmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Готовый товар',
                'verbose_name_plural': 'Готовые товары',
            },
        ),
    ]
