# Generated by Django 4.1.1 on 2022-10-06 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0012_finalproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
        ),
    ]
