# Generated by Django 4.1.1 on 2022-10-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_clothmodel_price_vyazka'),
        ('fabrika', '0013_finalproduction_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vyazka',
            options={'verbose_name': 'Вязка материала', 'verbose_name_plural': 'Распределение на вязку материала'},
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя Фамилия')),
                ('client_balance', models.FloatField(verbose_name='Баланс клиента')),
                ('client_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.clothmodel', verbose_name='Заказанная модель товара')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'База клиентов',
            },
        ),
    ]
