# Generated by Django 4.1.1 on 2022-10-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0014_alter_vyazka_options_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество заказа'),
        ),
        migrations.AddField(
            model_name='clients',
            name='client_status',
            field=models.BooleanField(default=False, verbose_name='Статус готовности'),
        ),
    ]
