# Generated by Django 4.1.1 on 2022-10-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0017_product_alter_finalproduction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество в партии'),
        ),
    ]
