# Generated by Django 4.1.1 on 2022-10-19 16:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0018_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region='UZ', verbose_name='Номер телефона'),
        ),
    ]
