# Generated by Django 4.1.1 on 2022-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0019_clients_client_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название группы работника')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='fabrika.employeegroups', verbose_name='Группа'),
        ),
    ]
