# Generated by Django 4.1.1 on 2022-10-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0020_employeegroups_employee_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeegroups',
            options={'verbose_name': 'Группа работников', 'verbose_name_plural': 'Группы работников'},
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='averlock_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='averlock', to='fabrika.employee', verbose_name='Работник Аверлок'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='bichuv_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bichuv', to='fabrika.employee', verbose_name='Работник Бичув'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='chistka_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chistka', to='fabrika.employee', verbose_name='Работник Чистка'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='chok_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chok', to='fabrika.employee', verbose_name='Работник Чок'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='dazmol_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dazmol', to='fabrika.employee', verbose_name='Работник Дазмол'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='jemchug_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jemchug', to='fabrika.employee', verbose_name='Работник Жемчуг'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='katelniy_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='katelniy', to='fabrika.employee', verbose_name='Работник Кательни'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='petlya_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petlya', to='fabrika.employee', verbose_name='Работник Петля'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='tugma_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tugma', to='fabrika.employee', verbose_name='Работник Тугма'),
        ),
        migrations.AlterField(
            model_name='clothproductmodel',
            name='upakovka_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upakovka', to='fabrika.employee', verbose_name='Работник Упаковка'),
        ),
    ]
