# Generated by Django 4.1.1 on 2022-10-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0021_alter_employeegroups_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_brak', models.FloatField(default=0, help_text='Заполнить после того, как работник сделал вязку', verbose_name='Масса брака')),
                ('sum_shtraf', models.FloatField(verbose_name='Сумма штрафа')),
                ('status', models.BooleanField(default=False, verbose_name='Починил ли брак')),
                ('vyazka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabrika.vyazka')),
            ],
            options={
                'verbose_name': 'Брак',
                'verbose_name_plural': 'Таблица брака',
            },
        ),
    ]
