# Generated by Django 4.1 on 2022-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrika', '0022_brak'),
    ]

    operations = [
        migrations.AddField(
            model_name='brak',
            name='count_edit',
            field=models.IntegerField(default=0, verbose_name='Кол-во изменений'),
        ),
    ]
